package cn.rsna.entity;

import java.io.Serializable;

public class UserPic implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpic.picid
     *
     * @mbggenerated
     */
    private Integer picid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpic.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpic.xmin
     *
     * @mbggenerated
     */
    private String xmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpic.ymin
     *
     * @mbggenerated
     */
    private String ymin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpic.xmax
     *
     * @mbggenerated
     */
    private String xmax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpic.ymax
     *
     * @mbggenerated
     */
    private String ymax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpic.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userpic
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpic.picid
     *
     * @return the value of userpic.picid
     *
     * @mbggenerated
     */
    public Integer getPicid() {
        return picid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpic.picid
     *
     * @param picid the value for userpic.picid
     *
     * @mbggenerated
     */
    public void setPicid(Integer picid) {
        this.picid = picid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpic.userid
     *
     * @return the value of userpic.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpic.userid
     *
     * @param userid the value for userpic.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpic.xmin
     *
     * @return the value of userpic.xmin
     *
     * @mbggenerated
     */
    public String getXmin() {
        return xmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpic.xmin
     *
     * @param xmin the value for userpic.xmin
     *
     * @mbggenerated
     */
    public void setXmin(String xmin) {
        this.xmin = xmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpic.ymin
     *
     * @return the value of userpic.ymin
     *
     * @mbggenerated
     */
    public String getYmin() {
        return ymin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpic.ymin
     *
     * @param ymin the value for userpic.ymin
     *
     * @mbggenerated
     */
    public void setYmin(String ymin) {
        this.ymin = ymin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpic.xmax
     *
     * @return the value of userpic.xmax
     *
     * @mbggenerated
     */
    public String getXmax() {
        return xmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpic.xmax
     *
     * @param xmax the value for userpic.xmax
     *
     * @mbggenerated
     */
    public void setXmax(String xmax) {
        this.xmax = xmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpic.ymax
     *
     * @return the value of userpic.ymax
     *
     * @mbggenerated
     */
    public String getYmax() {
        return ymax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpic.ymax
     *
     * @param ymax the value for userpic.ymax
     *
     * @mbggenerated
     */
    public void setYmax(String ymax) {
        this.ymax = ymax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpic.path
     *
     * @return the value of userpic.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpic.path
     *
     * @param path the value for userpic.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path;
    }
}